# Generated by Django 4.0.1 on 2022-01-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linksinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=40)),
                ('pid', models.CharField(max_length=40)),
                ('ip', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('systemTime', models.DateTimeField(auto_now_add=True)),
                ('completionTime', models.DateTimeField()),
            ],
        ),
    ]
