# Generated by Django 4.0.1 on 2022-01-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_viewlinksdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewlinksdata',
            options={'ordering': ['id']},
        ),
    ]
